from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

VDJMATCH_QUERY_PATTERNS = ("query", "source", "left")
VDJMATCH_TARGET_PATTERNS = ("target", "match", "right")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Summarize pairwise vdjmatch2 outputs for YFV day15/F1 AIRR files and "
            "build overlap matrices for downstream heatmap plotting."
        )
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("/projects/immunestatus/pogorelyy/airr_format"),
        help="Directory with source AIRR tables, e.g. P1_15_F1.txt.",
    )
    parser.add_argument(
        "--matches-dir",
        type=Path,
        default=Path("results") / "yfv_vdjmatch2" / "day15_f1_matches",
        help="Directory with pairwise vdjmatch2 outputs generated by run_vdjmatch2_day15_f1.sh.",
    )
    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=Path("results") / "yfv_vdjmatch2" / "pairwise_overlap" / "yfv_day15_f1_vdjmatch2",
        help="Prefix for summary TSV files and matrices.",
    )
    parser.add_argument(
        "--sample-pattern",
        default="*_15_F1.txt",
        help="Glob for selecting source samples inside --input-dir.",
    )
    parser.add_argument(
        "--chain",
        default="beta",
        help="Keep only rows with this locus value.",
    )
    return parser.parse_args()


def normalize_cdr3(series: pd.Series) -> pd.Series:
    return series.fillna("").astype(str).str.strip().str.upper()


def load_sample_clonotypes(sample_path: Path, chain: str) -> set[str]:
    df = pd.read_csv(sample_path, sep="\t")
    required_cols = {"junction_aa", "locus"}
    missing = required_cols.difference(df.columns)
    if missing:
        raise ValueError(f"{sample_path} is missing required columns: {sorted(missing)}")
    mask = df["locus"].fillna("").astype(str).str.strip().str.lower().eq(chain.strip().lower())
    cdr3 = normalize_cdr3(df.loc[mask, "junction_aa"])
    cdr3 = cdr3[cdr3.ne("")]
    return set(cdr3.tolist())


def sample_id_from_path(path: Path) -> str:
    return path.name.removesuffix(".txt").removesuffix(".txt.gz")


def donor_id_from_sample_id(sample_id: str) -> str:
    return sample_id.split("_", 1)[0]


def load_samples(input_dir: Path, sample_pattern: str, chain: str) -> tuple[dict[str, set[str]], pd.DataFrame]:
    sample_paths = sorted(input_dir.glob(sample_pattern))
    if not sample_paths:
        raise FileNotFoundError(f"No sample files matched '{sample_pattern}' in {input_dir}")

    sample_to_clonotypes: dict[str, set[str]] = {}
    records: list[dict[str, object]] = []
    for sample_path in sample_paths:
        sample_id = sample_id_from_path(sample_path)
        clonotypes = load_sample_clonotypes(sample_path, chain=chain)
        sample_to_clonotypes[sample_id] = clonotypes
        records.append(
            {
                "sample_id": sample_id,
                "donor": donor_id_from_sample_id(sample_id),
                "sample_path": str(sample_path),
                "n_unique_clonotypes": len(clonotypes),
            }
        )
    metadata = pd.DataFrame.from_records(records).sort_values("sample_id").reset_index(drop=True)
    return sample_to_clonotypes, metadata


def find_prefixed_cdr3_column(df: pd.DataFrame, side_patterns: tuple[str, ...]) -> str:
    cdr3_like = [col for col in df.columns if any(token in col.lower() for token in ("junction", "cdr3"))]
    for pattern in side_patterns:
        for col in cdr3_like:
            if pattern in col.lower():
                return col
    raise ValueError(
        "Could not infer vdjmatch2 CDR3 column for patterns "
        f"{side_patterns}; available CDR3-like columns: {cdr3_like}"
    )


def load_match_table(match_path: Path) -> pd.DataFrame:
    if not match_path.exists():
        raise FileNotFoundError(f"Match file not found: {match_path}")
    try:
        df = pd.read_csv(match_path, sep="\t")
    except pd.errors.EmptyDataError:
        return pd.DataFrame()
    if df.empty:
        return df
    query_col = find_prefixed_cdr3_column(df, VDJMATCH_QUERY_PATTERNS)
    target_col = find_prefixed_cdr3_column(df, VDJMATCH_TARGET_PATTERNS)
    result = pd.DataFrame(
        {
            "query_cdr3": normalize_cdr3(df[query_col]),
            "target_cdr3": normalize_cdr3(df[target_col]),
        }
    )
    return result.loc[result["query_cdr3"].ne("") & result["target_cdr3"].ne("")].drop_duplicates()


def build_matrix(pairwise_df: pd.DataFrame, value_col: str) -> pd.DataFrame:
    return (
        pairwise_df.pivot(index="sample_x", columns="sample_y", values=value_col)
        .sort_index(axis=0)
        .sort_index(axis=1)
    )


def compute_pairwise_overlap(
    sample_to_clonotypes: dict[str, set[str]],
    matches_dir: Path,
) -> pd.DataFrame:
    sample_ids = sorted(sample_to_clonotypes)
    records: list[dict[str, object]] = []

    for sample_x in sample_ids:
        clonotypes_x = sample_to_clonotypes[sample_x]
        n_x = len(clonotypes_x)
        for sample_y in sample_ids:
            clonotypes_y = sample_to_clonotypes[sample_y]
            n_y = len(clonotypes_y)

            if sample_x == sample_y:
                matched_query = set(clonotypes_x)
                n_pairs = n_x
            else:
                match_path = matches_dir / f"{sample_x}__vs__{sample_y}.tsv"
                match_df = load_match_table(match_path)
                matched_query = set(match_df["query_cdr3"]) if not match_df.empty else set()
                n_pairs = len(match_df)

            share_x_in_y = len(matched_query) / n_x if n_x else 0.0
            records.append(
                {
                    "sample_x": sample_x,
                    "sample_y": sample_y,
                    "donor_x": donor_id_from_sample_id(sample_x),
                    "donor_y": donor_id_from_sample_id(sample_y),
                    "n_clonotypes_x": n_x,
                    "n_clonotypes_y": n_y,
                    "n_matched_pairs": n_pairs,
                    "n_matched_x_in_y": len(matched_query),
                    "share_x_in_y": share_x_in_y,
                }
            )

    return pd.DataFrame.from_records(records)


def main() -> None:
    args = parse_args()
    args.output_prefix.parent.mkdir(parents=True, exist_ok=True)

    sample_to_clonotypes, metadata = load_samples(args.input_dir, args.sample_pattern, args.chain)
    pairwise_df = compute_pairwise_overlap(sample_to_clonotypes, args.matches_dir)

    matrix = build_matrix(pairwise_df, "share_x_in_y")

    metadata_path = args.output_prefix.with_name(args.output_prefix.name + "_sample_metadata.tsv")
    pairwise_path = args.output_prefix.with_name(args.output_prefix.name + "_pairwise.tsv")
    default_matrix_path = args.output_prefix.with_name(args.output_prefix.name + "_matrix.tsv")

    metadata.to_csv(metadata_path, sep="\t", index=False)
    pairwise_df.to_csv(pairwise_path, sep="\t", index=False)
    matrix.to_csv(default_matrix_path, sep="\t")

    print(f"Saved sample metadata to {metadata_path}")
    print(f"Saved pairwise overlap table to {pairwise_path}")
    print(f"Saved default overlap matrix to {default_matrix_path}")
    print(metadata[["sample_id", "donor", "n_unique_clonotypes"]].to_string(index=False))


if __name__ == "__main__":
    main()
